# Generated by Django 4.1.7 on 2023-03-19 14:24

from django.db import migrations, models
import librarymanageapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.PositiveIntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('book_id', models.PositiveIntegerField()),
                ('book_name', models.CharField(max_length=200)),
                ('issued_date', models.DateField(auto_now=True)),
                ('to_be_return_date', models.DateField(default=librarymanageapp.models.to_be_return_date)),
                ('fine', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PendingIssueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('book_id', models.PositiveIntegerField()),
                ('book_name', models.CharField(max_length=200)),
                ('fine', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('book_id', models.PositiveIntegerField()),
                ('book_name', models.CharField(max_length=200)),
                ('return_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
