# Generated by Django 4.1.7 on 2023-03-21 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanageapp', '0002_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='session_key',
        ),
    ]
