# Generated by Django 4.1.7 on 2023-04-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanageapp', '0003_remove_usersession_session_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
